# deeptrack.math

<a href="https://colab.research.google.com/github/DeepTrackAI/DeepTrack2/blob/develop/tutorials/3-advanced-topics/DTAT381_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install deeptrack  # Uncomment if running on Colab/Kaggle.

This advanced tutorial introduces the module deeptrack.math.

In [2]:
import numpy as np

## 1. What is included in math?

The module math.py includes features that perform some mathematical operation on the input image. This can be used to normalize images, or merge several features.

## 2. Clip

Clips the input within a minimum and a maximum value.

In [3]:
import deeptrack.math as math

input_image = np.array(
    [
        [10, 4],
        [4, -10],
    ]
)

clip = math.Clip(min=-5, max=5)

print(input_image)
print("becomes")
print(clip.resolve(input_image))

[[ 10   4]
 [  4 -10]]
becomes
[[ 5  4]
 [ 4 -5]]


## 3. NormalizeMinMax

Transforms the input to be between a minimum and a maximum value using a linear transformation.

In [4]:
input_image = np.array(
    [
        [10, 4],
        [4, -10],
    ]
)

feature = math.NormalizeMinMax(min=-5, max=5)

print(input_image)
print("becomes")
print(feature.resolve(input_image))

[[ 10   4]
 [  4 -10]]
becomes
[[ 5.  2.]
 [ 2. -5.]]
