In [1]:
%matplotlib inline
import sys
sys.path.append("..") # Adds the module to path

# deeptrack.math

This example introduces the module deeptrack.math.

## 1. What is included in math?

The module math.py includes features that perform some mathematical operation on the input image. This can be used to normalize images, or merge several features.

## 2. Setup

In [2]:
import deeptrack.math as math
import numpy as np

## 3. Clip

Clip the input within a minimum and a maximum value.

In [3]:
input_image = np.array([[10, 4], [4, -10]])

feature = math.Clip(min=-5, max=5)

print(input_image)
print("becomes")
print(feature.resolve(input_image))

[[ 10   4]
 [  4 -10]]
becomes
[[ 5  4]
 [ 4 -5]]


## 4. NormalizeMinMax

Transforms the input to be between a minimum and a maximum value using a linear transformation.

In [4]:
input_image = np.array([[10, 4], [4, -10]])

feature = math.NormalizeMinMax(min=-5, max=5)

print(input_image)
print("becomes")
print(feature.resolve(input_image))

[[ 10   4]
 [  4 -10]]
becomes
[[ 5.  2.]
 [ 2. -5.]]
